### PR TITLE
fix: content empty when importing dupe

### PR DESCRIPTION
**Pull request by DevVersion**
Currently when a file `Y` is imported twice from a file `X`. Then the full content of `X` will be empty. The import statement should be just removed, and the content of file `X` should still exist.

Not really 100% sure about it, but this fixes the issue I ran into.

### CODE REVIEW

**Comment by DovydasNavickas** [comment]
Maybe we should indicate that an import was deduped at a particular place? A comment as with an unfound import could be better than just an empty string, don't you think?

It wouldn't take much space and would be quite functional.

**Comment by DevVersion** [comment]
I'm not really sure. I'm worried about replacing with comments because some people don't run a minimizer after (Material 2 intentionally) and therefore the SCSS bundle would look dirty.

How about warnings that can be silenced? Same for not found comments.

**Comment by DovydasNavickas** [comment]
Maybe adding yet another configuration point, e.g. `outputVerbosity` would do?
The CLI gets a bit cluttered, but I suppose if you're using all of the options, you either use the configuration file or consume `scss-bundle` via TypeScript either way.

What do you think?

**Comment by DovydasNavickas** [comment]
Another wild idea would be adding a `--debug` flag that enables `--verbosity Verbose` and `outputVerbosity Verbose` too. That might make it easier to use it when needed and skip it when releasing the bundled SCSS.

**Comment by DevVersion** [comment]
Yeah I think having both would be a good idea.

**Comment by DovydasNavickas** [comment]
I've opened the issues for both `--debug` flag ( #30) and `--outputVerbosity` (#29).

I've also merged and published this fix so that you can use it right away.

It's 3:49am at my place, so I'm gonna call it a day 😄  Cheers!

**Comment by DevVersion** [comment]
Thanl you very much! Yeah 2:50am for me as well 😄 Sleep well!

**Pull request merged**
